// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOVgJ5jOy3I739jQOoyO83tm_NiDrPlrg',
    appId: '1:968762389620:web:0fd845bc65de710238cd21',
    messagingSenderId: '968762389620',
    projectId: 'reelongo-b6c8c',
    authDomain: 'reelongo-b6c8c.firebaseapp.com',
    storageBucket: 'reelongo-b6c8c.firebasestorage.app',
    measurementId: 'G-TM5ZYN4MFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3o_xn_fZWg7lfSY7RjKsPmo3yi7410jA',
    appId: '1:968762389620:android:dfe1893ee53d992538cd21',
    messagingSenderId: '968762389620',
    projectId: 'reelongo-b6c8c',
    storageBucket: 'reelongo-b6c8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0qRsKDxD78-ZlrbLSJ46D3OYMbdUr54',
    appId: '1:968762389620:ios:d9540b66025f04ec38cd21',
    messagingSenderId: '968762389620',
    projectId: 'reelongo-b6c8c',
    storageBucket: 'reelongo-b6c8c.firebasestorage.app',
    iosBundleId: 'com.example.reelOnGo',
  );
}
